---
- hosts: wordpress_nodes
  become: yes
  tasks:
    - name: "Let's create some Hello World file"
      file:
        path: ~/HelloWorld
        state: touch
    - name: "install apache server"
      yum:
        name: httpd
        state: latest
    - name: "Install php"
      yum:
        name: "{{item}}"
        state: latest
      with_items:
        - php
        - php-mysql
    - name: "Install db server"
      yum:
        name: "{{item}}"
      with_items:
        - mariadb
        - mariadb-server
    - service:
        name: mariadb
        state: started
    - name: "download wordpress "
      get_url:
        url: https://pl.wordpress.org/wordpress-4.9.8-pl_PL.tar.gz
        dest: ~/wordpress.tar.gz
    - name: "unarchive wordpress archive"
      unarchive:
        src: ~/wordpress.tar.gz
        dest: /var/www/
        remote_src: yes
    - name: "install additionall mysql puthon dependencies"
      yum:
        name: MySQL-python
        state: present
    - name: "Set up database"
      mysql_db:
        name: adsk_wordpress
        state: present
    - name: "configure apache vhost"
      copy:
        src: template/vhosts.conf
        dest: /etc/httpd/conf.d/wordpress.conf
    - name: "Start httpd server: "
      service:
        name: httpd
        state: restarted
    - name: "Copy wordpress config to destination"
      copy:
       src: template/wp-config.php
       dest: /var/www/wordpress
